### ISSUE TITLE
Task2 - Image Pre-Processing

### ISSUE THREAD

**Issue by breakthe-rule** [opencodeiiita/Medical-Image-Classification#31]
This task is open for all. No need to claim the issue.

In notebook *[Task2.ipynb](https://github.com/opencodeiiita/Medical-Image-Classification/blob/main/Task2.ipynb)* first add code of *[Task1.ipynb](https://github.com/opencodeiiita/Medical-Image-Classification/blob/main/Task1.ipynb)* done by you in previous issue as instructed.

Upload link of final colab file in folder *[Task2_solutions](https://github.com/opencodeiiita/Medical-Image-Classification/tree/main/Task2_solutions) * creating txt file with name as your **Enrollment/roll number**. Link should be in read mode and **access** to *iit2022119@iiita.ac.in*. (Don't make file public).

Only complete task till plotting pre-processed images and send PR for this issue.

For resources refer [Task2_Resources.txt](https://github.com/opencodeiiita/Medical-Image-Classification/blob/main/Task2_Resources.txt)

**Comment by rnavaneeth992** [comment]
claim

**Comment by QuantTitan** [comment]
claim
