### ISSUE TITLE
Task2 - Image Augmentation

### ISSUE THREAD

**Issue by breakthe-rule** [opencodeiiita/Medical-Image-Classification#33]
This task is open for all. No need to claim the issue.

Once your PR is merged for **Pre-Processing task**, start work on remaining portion of task i.e augmentation. Continue to work in same notebook you worked for Pre-processing..

Upload link of final colab file in folder *[Task2_solutions](https://github.com/opencodeiiita/Medical-Image-Classification/tree/main/Task2_solutions) * creating txt file with name as your Enrollment/roll number. Link should be in read mode and access to [iit2022119@iiita.ac.in](mailto:iit2022119@iiita.ac.in). (Don't make file public). Refer [Example.txt](https://github.com/opencodeiiita/Medical-Image-Classification/blob/main/Task2_solutions/Example.txt)

For resources refer [Task2_Resources.txt](https://github.com/opencodeiiita/Medical-Image-Classification/blob/main/Task2_Resources.txt)

**Comment by QuantTitan** [comment]
claim

**Comment by optimus-pride** [comment]
Claim
