### ISSUE TITLE
Task3 - Binary classification

### ISSUE THREAD

**Issue by breakthe-rule** [opencodeiiita/Medical-Image-Classification#69]
The moment has come when you will train and test your model.

This is a competitive task and only the best model (based on ROC-AUC score and is model underfit or overfit). All other correct PR will be awarded 10 points. This issue is live till **20 dec, 23:59 !!**

Make sure to setup GPU before start training.

Notebook: Task3.ipynb

Submit ur output in [Task3_solutions](https://github.com/opencodeiiita/Medical-Image-Classification/tree/main/Task3_solutions). Inside this folder create a folder name <roll _number> and inside this add saved model ( .h5) and a txt file containing link of colab file. 
**Note**: You have to submit both saved model and txt file

Edit:- Use only CNN (do not use pre-trained models). And while submitting output also submit all three graphs in jpeg format. And add test ROC-AUC score in txt file with file link.

**Comment by kushal7201** [comment]
Claim

**Comment by AngadManroy** [comment]
Claim

**Comment by breakthe-rule** [comment]
No need to claim this issue. best model will be selected. everyone can make prs
