### ISSUE TITLE
Task4

### ISSUE THREAD

**Issue by breakthe-rule** [opencodeiiita/Medical-Image-Classification#79]
Up to now you have trained your own CNN, now lets make predictions using **pre-trained models**.

This is a competitive task and only the best model (based on ROC-AUC score and is model underfit or overfit). All other correct PR will be awarded 10 points. This issue is live till 23 dec, 23:59 !!

Make sure to setup GPU before start training.

Notebook: Task4.ipynb

This is binary classification. 

Submit ur output in [Task4_solutions](https://github.com/opencodeiiita/Medical-Image-Classification/tree/main/Task4_solutions). Inside this folder create a folder name and inside this add saved model and a txt file containing link of colab file.

1. You have to submit both saved model and txt file
2. While submitting output also submit all three graphs in jpeg format. 
3. Add test ROC-AUC score in txt file with file link.

**Comment by abhisheksharma010** [comment]
Claim

**Comment by breakthe-rule** [comment]
@abhisheksharma010 no need to claim this issue

**Comment by rnavaneeth992** [comment]
@breakthe-rule What we have to do exactly (Up to now you have trained your own CNN, now lets make predictions using pre-trained models) Predictions -> on test dataset ?

**Comment by breakthe-rule** [comment]
> @breakthe-rule What we have to do exactly (Up to now you have trained your own CNN, now lets make predictions using pre-trained models) Predictions -> on test dataset ?

Yes
