### ISSUE TITLE
Lets deploy !!

### ISSUE THREAD

**Issue by breakthe-rule** [opencodeiiita/Medical-Image-Classification#89]
# Moment has come to deploy your model !!🎉

Use <ins>*streamlit*</ins> to deploy your DL model you have made so far. (You can use one of the two models that were made.)

May refer tutorials on youtube to learn how to deploy on streamlit platform.

<ins>How to submit</ins>:
* Create a folder of your name and in this add your code and a txt file with link to website.
* Example link: https://1st-deployment.streamlit.app/

**Most beautiful website will be awarded maximum points.**

*Edit: Only best website will be awarded points. And there might be case, where no PR will be merged if your website is not found much attractive. Include graphics, animations, icons, fonts and many other ways to make it attractive.*

**Comment by kushal7201** [comment]
Claim
